services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - users-service

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - users-service
      - reservations-service

  users-service:
    build:
      context: ./usersService
      dockerfile: Dockerfile
    env_file:
      - ./usersService/.env
    volumes:
      - ./usersService:/usr/src/app
    ports:
      - "4000:4000"
    depends_on:
      - users-db
    command: >
      sh -c "wait-for-it.sh users-db:5432 -- npx prisma generate --schema=./prisma/schema.prisma && npx prisma migrate deploy --schema=./prisma/schema.prisma && npm start"

  reservations-service:
    build:
      context: ./reservationsService
      dockerfile: Dockerfile
    env_file:
      - ./reservationsService/.env
    volumes:
      - ./reservationsService:/usr/src/app
    ports:
      - "4001:4001"
    depends_on:
      - reservations-db
    command: >
      sh -c "wait-for-it.sh reservations-db:5432 --
            npx prisma generate --schema=./prisma/schema.prisma &&
            npx prisma migrate deploy --schema=./prisma/schema.prisma &&
            npm start"

  reservations-db:
    image: postgres:15
    environment:
      POSTGRES_USER: reservations_user
      POSTGRES_PASSWORD: reservations_password
      POSTGRES_DB: reservations
    volumes:
      - reservations_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  users-db:
    image: postgres:15
    environment:
      POSTGRES_USER: users_user
      POSTGRES_PASSWORD: users_password
      POSTGRES_DB: users
    volumes:
      - users_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  users_data:
  reservations_data:
