services:
  web:
    build:
      context: ../apps/web
      dockerfile: Dockerfile.dev
    container_name: kombi_web
    ports:
      - "3000:3000"
    volumes:
      - ../apps/web:/usr/src/app
    env_file:
      - ../apps/web/.env.dev
    environment:
      - NODE_ENV=development
    depends_on:
      - users
      - booking
    networks:
      - kombi_network

  users:
    build:
      context: ../services/users
      dockerfile: Dockerfile.dev
    container_name: kombi_users
    volumes:
      - ../services/users:/usr/src/app
    ports:
      - "4001:4001"
    env_file:
      - ../services/users/.env.dev
    environment:
      - NODE_ENV=development
    depends_on:
      - users-db
    networks:
      - kombi_network

  booking:
    build:
      context: ../services/booking
      dockerfile: Dockerfile.dev
    container_name: kombi_booking
    volumes:
      - ../services/booking:/usr/src/app
    ports:
      - "4002:4002"
    env_file:
      - ../services/booking/.env.dev
    environment:
      - NODE_ENV=development
    depends_on:
      - booking-db
    networks:
      - kombi_network

  users-db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    networks:
      - kombi_network

  booking-db:
    image: postgres:15
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=booking
    networks:
      - kombi_network

  nginx:
    build:
      context: ../infra/nginx
      dockerfile: Dockerfile.dev
    container_name: kombi_nginx
    ports:
    - "80:80"
    - "443:443"
    volumes:
      - ../infra/certs:/certs:ro
    depends_on:
      - web
      - users
      - booking
    networks:
      - kombi_network

networks:
  kombi_network:
    driver: bridge
